import os
import shutil
import sys

def install_nodeos():
    print("\033[96m=== [ AGY-NodeOS Global Installer ] ===\033[0m")
    
    # Define paths
    home_dir = os.path.expanduser("~")
    gemini_config_dir = os.path.join(home_dir, ".gemini", "config")
    
    global_rules_dir = os.path.join(gemini_config_dir, "rules")
    global_skills_dir = os.path.join(gemini_config_dir, "skills")
    
    nodeos_skill_dest = os.path.join(global_skills_dir, "agy-nodeos-installer")
    
    # 1. Ensure global config directories exist
    os.makedirs(global_rules_dir, exist_ok=True)
    os.makedirs(nodeos_skill_dest, exist_ok=True)
    print("\033[90m[+] Verified Antigravity Global Customization Roots.\033[0m")
    
    # 2. Install the Global Rule
    rule_content = """---
trigger: always_on
---
# Universal NodeOS Enforcement Rule

Whenever the USER requests to start a new project, resume a project, or build software within the Android Termux environment, you MUST natively use AGY-NodeOS as the core operating and execution environment.

**Procedure:**
1. Check if the project contains an `.agents/hooks.json` file.
2. If it does not, you must initialize AGY-NodeOS by executing the `agy-nodeos-installer` skill protocols to copy the hooks and prepare the environment.
3. You must act as the External Swarm Intelligence, parsing `workflow.json` intents emitted by the NodeOS daemon and executing them using your sub-agents.
4. You must read `telemetry.py` logs or execute it to gauge the intent states (Pending -> Running -> Completed).
5. All code restructuring, AST mappings, and complex multi-file intelligence MUST leverage the SQLite graph generated by NodeOS. **Do NOT use grep or manual file parsing for codebase context.**

# CRITICAL OVERRIDE: NodeOS Native Interaction Paradigm
Whenever operating inside a NodeOS-managed workspace (e.g., ~/Projects/SysTune), you are the primary intelligence driving the state.

1. You MUST use your highly-optimized, built-in system tools (`view_file`, `list_dir`, `replace_file_content`) to interact directly with the file system.
2. You MUST NOT use deprecated MCP standalone wrappers (like `nodeos_read.py` or `nodeos_search.py`).
3. For spatial architectural insight and dependency resolution, use the `run_command` tool to query the SQLite database natively (e.g., `sqlite3 agy_nodeos.db "SELECT * FROM nodes;"`).
4. For task dispatching and swarm intent, directly modify `workflow.json` at the root of the workspace. The NodeOS watchdog will automatically pick up and execute your JSON drops.
"""
    rule_path = os.path.join(global_rules_dir, "nodeos_standard.md")
    with open(rule_path, "w") as f:
        f.write(rule_content)
    print(f"\033[92m[+] Installed Global Rule -> {rule_path}\033[0m")
    
    # 3. Install the Skill
    local_skill_path = os.path.join(os.getcwd(), "skills", "agy-nodeos-installer", "SKILL.md")
    if os.path.exists(local_skill_path):
        dest_skill_file = os.path.join(nodeos_skill_dest, "SKILL.md")
        shutil.copy(local_skill_path, dest_skill_file)
        print(f"\033[92m[+] Installed Global Skill -> {dest_skill_file}\033[0m")
    else:
        print(f"\033[91m[-] Error: Could not find local skill at {local_skill_path}\033[0m")
        sys.exit(1)
    # MCP Server has been fully deprecated in favor of native hooks and local `.agents/rules/`.
        
    print("\n\033[96m[ NodeOS Successfully Injected into Antigravity Global Brain! ]\033[0m")

if __name__ == "__main__":
    install_nodeos()
