[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "polymath-nodeos"
version = "1.0.0"
description = "A zero-dependency Autonomous Agentic Swarm Operating System."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [
  { name="Polymath Void" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.scripts]
polymath-nodeos-daemon = "polymath_nodeos.daemon:daemonize_and_run"
polymath-nodeos-injector = "polymath_nodeos.scripts.intent_injector:main"
polymath-nodeos-stopper = "polymath_nodeos.scripts.intent_stopper:main"

[tool.setuptools.packages.find]
include = ["polymath_nodeos*"]
