import os
import sys

def install_nodeos():
    print("\033[96m=== [ AGY-NodeOS Global Installer ] ===\033[0m")
    
    # Define paths
    home_dir = os.path.expanduser("~")
    gemini_config_dir = os.path.join(home_dir, ".gemini", "config")
    
    global_rules_dir = os.path.join(gemini_config_dir, "rules")
    global_skills_dir = os.path.join(gemini_config_dir, "skills")
    
    nodeos_skill_dest = os.path.join(global_skills_dir, "agy-nodeos-installer")
    
    # 1. Ensure global config directories exist
    os.makedirs(global_rules_dir, exist_ok=True)
    os.makedirs(nodeos_skill_dest, exist_ok=True)
    print("\033[90m[+] Verified Antigravity Global Customization Roots.\033[0m")
    
    # 2. Install the Global Rule
    rule_content = """---
trigger: always_on
---
# Universal NodeOS Enforcement Rule

Whenever the USER requests to start a new project, resume a project, or build software within the Android Termux environment, you MUST natively use AGY-NodeOS as the core operating and execution environment.

**Procedure:**
1. Check if the project contains an `.agents/hooks.json` file.
2. If it does not, you must initialize AGY-NodeOS by executing the `agy-nodeos-installer` skill protocols to copy the hooks and prepare the environment.
3. You must act as the External Swarm Intelligence, parsing `workflow.json` intents emitted by the NodeOS daemon and executing them using your sub-agents.
4. You must read `scripts/telemetry.py` logs or execute it to gauge the intent states (Pending -> Running -> Completed).
5. All code restructuring, AST mappings, and complex multi-file intelligence MUST leverage the SQLite graph generated by NodeOS. **Do NOT use grep or manual file parsing for codebase context.**

# CRITICAL OVERRIDE: NodeOS Native Interaction Paradigm
Whenever operating inside a NodeOS-managed workspace (e.g., ~/Projects/SysTune), you are the primary intelligence driving the state.

1. You MUST use your highly-optimized, built-in system tools (`view_file`, `list_dir`, `replace_file_content`) to interact directly with the file system.
2. You MUST NOT use deprecated MCP standalone wrappers (like `nodeos_read.py` or `nodeos_search.py`).
3. For spatial architectural insight and dependency resolution, use the `run_command` tool to query the SQLite database natively (e.g., `sqlite3 agy_nodeos.db "SELECT * FROM nodes;"`).
4. For task dispatching and swarm intent, directly modify `workflow.json` at the root of the workspace. The NodeOS watchdog will automatically pick up and execute your JSON drops.
"""
    rule_path = os.path.join(global_rules_dir, "nodeos_standard.md")
    with open(rule_path, "w") as f:
        f.write(rule_content)
    print(f"\033[92m[+] Installed Global Rule -> {rule_path}\033[0m")
    
    # 3. Install the Skill
    skill_content = """---
name: agy-nodeos-installer
description: Standard Operating Procedure for injecting and activating the AGY-NodeOS background daemon and hook into a target workspace.
---

# AGY-NodeOS Injection Protocol

Whenever you are tasked with initializing a project or establishing the AGY-NodeOS 24/7 background architecture in a workspace, you MUST follow these steps to inject the lifecycle hooks.

## 1. Verify Target Workspace
Ensure you are operating inside the intended project directory. If the project does not have a local `.agents` folder, you must create it:
```bash
mkdir -p .agents
```

## 2. Copy the Lifecycle Hook
The master hook file resides in the core AGY-NodeOS repository. You must copy it into the local project's `.agents` directory so the Antigravity CLI binds the daemon to the workspace.
```bash
cp ~/.gemini/config/skills/agy-nodeos-installer/hooks.json .agents/hooks.json
```

## 3. Validate Daemon Boot
Once the hook is copied, the `agy-nodeos-boot` script will automatically trigger on the very next `PreInvocation` event (which means the next time the agent is prompted). 

The hook executes the following:
`pgrep -f 'nodeos -d' > /dev/null || (nohup nodeos -d > daemon.log 2>&1 &)`

This guarantees the native Python AST Engine, SQLite Graph Manager, and QuadTree Spatial Physics Matrix are running silently in the background 24/7.

## 4. Sub-Agent Intent Handling
Do NOT manually run `python daemon.py` in the terminal. The hook handles it autonomously.

Remember that AGY-NodeOS is completely decoupled from execution logic. It acts purely as a physical environment and **Intent Emitter**. 
When you (the main agent) observe `workflow.json` transitioning to `"status": "pending"`, you must use your `invoke_subagent` tool to spawn a specialized AGY agent to perform the task. 

## 5. Native Codebase Context (Search Protocol)
When operating inside an AGY-NodeOS initialized workspace, you are strictly prohibited from relying on manual `grep` scans for structural understanding. 
Instead, rely on the native Graph Database by querying the search utility:
```bash
nodeos -c search "<TargetClassNameOrFunction>"
```
"""
    dest_skill_file = os.path.join(nodeos_skill_dest, "SKILL.md")
    with open(dest_skill_file, "w") as f:
        f.write(skill_content)
    print(f"\033[92m[+] Installed Global Skill -> {dest_skill_file}\033[0m")
        
    # 4. Install the Hooks Template
    hooks_content = """{
  "agy-nodeos-boot": {
    "PreInvocation": [
      {
        "type": "command",
        "command": "pgrep -f 'nodeos -d' > /dev/null || (nohup nodeos -d > daemon.log 2>&1 &)",
        "timeout": 5
      }
    ]
  },
  "nodeos-swarm-intent": {
    "PreInvocation": [
      {
        "type": "command",
        "command": "nodeos -s intent_injector"
      }
    ],
    "Stop": [
      {
        "type": "command",
        "command": "nodeos -s intent_stopper"
      }
    ]
  }
}
"""
    dest_hooks = os.path.join(nodeos_skill_dest, "hooks.json")
    with open(dest_hooks, "w") as f:
        f.write(hooks_content)
    print(f"\033[92m[+] Installed Global Hook Template -> {dest_hooks}\033[0m")
        
    print("\n\033[96m[ NodeOS Successfully Injected into Antigravity Global Brain! ]\033[0m")
    print("\033[93m[!] Note: You can now cd into any project and use NodeOS tools.\033[0m")

if __name__ == "__main__":
    install_nodeos()
